/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicLayoutImport } from './routes/_public-layout'
import { Route as AuthLayoutImport } from './routes/_auth-layout'
import { Route as PublicLayoutUnprotectedImport } from './routes/_public-layout/_unprotected'

// Create Virtual Routes

const PublicLayoutIndexLazyImport = createFileRoute('/_public-layout/')()
const AuthLayoutIncomeLazyImport = createFileRoute('/_auth-layout/income')()
const AuthLayoutExpensesLazyImport = createFileRoute('/_auth-layout/expenses')()
const AuthLayoutEnvelopesLazyImport = createFileRoute(
  '/_auth-layout/envelopes',
)()
const AuthLayoutDashboardLazyImport = createFileRoute(
  '/_auth-layout/dashboard',
)()
const PublicLayoutUnprotectedSignupLazyImport = createFileRoute(
  '/_public-layout/_unprotected/signup',
)()
const PublicLayoutUnprotectedLoginLazyImport = createFileRoute(
  '/_public-layout/_unprotected/login',
)()

// Create/Update Routes

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_public-layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const PublicLayoutIndexLazyRoute = PublicLayoutIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public-layout/index.lazy').then((d) => d.Route),
)

const AuthLayoutIncomeLazyRoute = AuthLayoutIncomeLazyImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_auth-layout/income.lazy').then((d) => d.Route),
)

const AuthLayoutExpensesLazyRoute = AuthLayoutExpensesLazyImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_auth-layout/expenses.lazy').then((d) => d.Route),
)

const AuthLayoutEnvelopesLazyRoute = AuthLayoutEnvelopesLazyImport.update({
  id: '/envelopes',
  path: '/envelopes',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_auth-layout/envelopes.lazy').then((d) => d.Route),
)

const AuthLayoutDashboardLazyRoute = AuthLayoutDashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_auth-layout/dashboard.lazy').then((d) => d.Route),
)

const PublicLayoutUnprotectedRoute = PublicLayoutUnprotectedImport.update({
  id: '/_unprotected',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const PublicLayoutUnprotectedSignupLazyRoute =
  PublicLayoutUnprotectedSignupLazyImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => PublicLayoutUnprotectedRoute,
  } as any).lazy(() =>
    import('./routes/_public-layout/_unprotected/signup.lazy').then(
      (d) => d.Route,
    ),
  )

const PublicLayoutUnprotectedLoginLazyRoute =
  PublicLayoutUnprotectedLoginLazyImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PublicLayoutUnprotectedRoute,
  } as any).lazy(() =>
    import('./routes/_public-layout/_unprotected/login.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_public-layout': {
      id: '/_public-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_public-layout/_unprotected': {
      id: '/_public-layout/_unprotected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutUnprotectedImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_auth-layout/dashboard': {
      id: '/_auth-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthLayoutDashboardLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth-layout/envelopes': {
      id: '/_auth-layout/envelopes'
      path: '/envelopes'
      fullPath: '/envelopes'
      preLoaderRoute: typeof AuthLayoutEnvelopesLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth-layout/expenses': {
      id: '/_auth-layout/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthLayoutExpensesLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth-layout/income': {
      id: '/_auth-layout/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthLayoutIncomeLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_public-layout/': {
      id: '/_public-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexLazyImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_public-layout/_unprotected/login': {
      id: '/_public-layout/_unprotected/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutUnprotectedLoginLazyImport
      parentRoute: typeof PublicLayoutUnprotectedImport
    }
    '/_public-layout/_unprotected/signup': {
      id: '/_public-layout/_unprotected/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicLayoutUnprotectedSignupLazyImport
      parentRoute: typeof PublicLayoutUnprotectedImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLayoutDashboardLazyRoute: typeof AuthLayoutDashboardLazyRoute
  AuthLayoutEnvelopesLazyRoute: typeof AuthLayoutEnvelopesLazyRoute
  AuthLayoutExpensesLazyRoute: typeof AuthLayoutExpensesLazyRoute
  AuthLayoutIncomeLazyRoute: typeof AuthLayoutIncomeLazyRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutDashboardLazyRoute: AuthLayoutDashboardLazyRoute,
  AuthLayoutEnvelopesLazyRoute: AuthLayoutEnvelopesLazyRoute,
  AuthLayoutExpensesLazyRoute: AuthLayoutExpensesLazyRoute,
  AuthLayoutIncomeLazyRoute: AuthLayoutIncomeLazyRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PublicLayoutUnprotectedRouteChildren {
  PublicLayoutUnprotectedLoginLazyRoute: typeof PublicLayoutUnprotectedLoginLazyRoute
  PublicLayoutUnprotectedSignupLazyRoute: typeof PublicLayoutUnprotectedSignupLazyRoute
}

const PublicLayoutUnprotectedRouteChildren: PublicLayoutUnprotectedRouteChildren =
  {
    PublicLayoutUnprotectedLoginLazyRoute:
      PublicLayoutUnprotectedLoginLazyRoute,
    PublicLayoutUnprotectedSignupLazyRoute:
      PublicLayoutUnprotectedSignupLazyRoute,
  }

const PublicLayoutUnprotectedRouteWithChildren =
  PublicLayoutUnprotectedRoute._addFileChildren(
    PublicLayoutUnprotectedRouteChildren,
  )

interface PublicLayoutRouteChildren {
  PublicLayoutUnprotectedRoute: typeof PublicLayoutUnprotectedRouteWithChildren
  PublicLayoutIndexLazyRoute: typeof PublicLayoutIndexLazyRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutUnprotectedRoute: PublicLayoutUnprotectedRouteWithChildren,
  PublicLayoutIndexLazyRoute: PublicLayoutIndexLazyRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicLayoutUnprotectedRouteWithChildren
  '/dashboard': typeof AuthLayoutDashboardLazyRoute
  '/envelopes': typeof AuthLayoutEnvelopesLazyRoute
  '/expenses': typeof AuthLayoutExpensesLazyRoute
  '/income': typeof AuthLayoutIncomeLazyRoute
  '/': typeof PublicLayoutIndexLazyRoute
  '/login': typeof PublicLayoutUnprotectedLoginLazyRoute
  '/signup': typeof PublicLayoutUnprotectedSignupLazyRoute
}

export interface FileRoutesByTo {
  '': typeof PublicLayoutUnprotectedRouteWithChildren
  '/dashboard': typeof AuthLayoutDashboardLazyRoute
  '/envelopes': typeof AuthLayoutEnvelopesLazyRoute
  '/expenses': typeof AuthLayoutExpensesLazyRoute
  '/income': typeof AuthLayoutIncomeLazyRoute
  '/': typeof PublicLayoutIndexLazyRoute
  '/login': typeof PublicLayoutUnprotectedLoginLazyRoute
  '/signup': typeof PublicLayoutUnprotectedSignupLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_public-layout': typeof PublicLayoutRouteWithChildren
  '/_public-layout/_unprotected': typeof PublicLayoutUnprotectedRouteWithChildren
  '/_auth-layout/dashboard': typeof AuthLayoutDashboardLazyRoute
  '/_auth-layout/envelopes': typeof AuthLayoutEnvelopesLazyRoute
  '/_auth-layout/expenses': typeof AuthLayoutExpensesLazyRoute
  '/_auth-layout/income': typeof AuthLayoutIncomeLazyRoute
  '/_public-layout/': typeof PublicLayoutIndexLazyRoute
  '/_public-layout/_unprotected/login': typeof PublicLayoutUnprotectedLoginLazyRoute
  '/_public-layout/_unprotected/signup': typeof PublicLayoutUnprotectedSignupLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/envelopes'
    | '/expenses'
    | '/income'
    | '/'
    | '/login'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/envelopes'
    | '/expenses'
    | '/income'
    | '/'
    | '/login'
    | '/signup'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/_public-layout'
    | '/_public-layout/_unprotected'
    | '/_auth-layout/dashboard'
    | '/_auth-layout/envelopes'
    | '/_auth-layout/expenses'
    | '/_auth-layout/income'
    | '/_public-layout/'
    | '/_public-layout/_unprotected/login'
    | '/_public-layout/_unprotected/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-layout",
        "/_public-layout"
      ]
    },
    "/_auth-layout": {
      "filePath": "_auth-layout.tsx",
      "children": [
        "/_auth-layout/dashboard",
        "/_auth-layout/envelopes",
        "/_auth-layout/expenses",
        "/_auth-layout/income"
      ]
    },
    "/_public-layout": {
      "filePath": "_public-layout.tsx",
      "children": [
        "/_public-layout/_unprotected",
        "/_public-layout/"
      ]
    },
    "/_public-layout/_unprotected": {
      "filePath": "_public-layout/_unprotected.tsx",
      "parent": "/_public-layout",
      "children": [
        "/_public-layout/_unprotected/login",
        "/_public-layout/_unprotected/signup"
      ]
    },
    "/_auth-layout/dashboard": {
      "filePath": "_auth-layout/dashboard.lazy.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/envelopes": {
      "filePath": "_auth-layout/envelopes.lazy.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/expenses": {
      "filePath": "_auth-layout/expenses.lazy.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/income": {
      "filePath": "_auth-layout/income.lazy.tsx",
      "parent": "/_auth-layout"
    },
    "/_public-layout/": {
      "filePath": "_public-layout/index.lazy.tsx",
      "parent": "/_public-layout"
    },
    "/_public-layout/_unprotected/login": {
      "filePath": "_public-layout/_unprotected/login.lazy.tsx",
      "parent": "/_public-layout/_unprotected"
    },
    "/_public-layout/_unprotected/signup": {
      "filePath": "_public-layout/_unprotected/signup.lazy.tsx",
      "parent": "/_public-layout/_unprotected"
    }
  }
}
ROUTE_MANIFEST_END */
